FROM ubuntu:16.04

USER root

RUN apt-get update && apt-get upgrade
RUN apt-get -y install curl wget sudo
RUN wget https://download.tizen.org/sdk/Installer/tizen-studio_1.1.1/web-ide_Tizen_Studio_1.1.1_ubuntu-64.bin -O /tmp/tizen-studio.bin
RUN chmod +x /tmp/tizen-studio.bin
RUN apt-get update && apt-get install -y apt-utils
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:webupd8team/java
RUN apt-get install -y zip
RUN echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | debconf-set-selections
RUN echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 seen true" | debconf-set-selections
RUN apt-get update && apt-get install -y oracle-java8-installer
RUN apt-get update && apt-get install -y oracle-java8-set-default
RUN apt-get install -y libswt-gtk-3-java cpio rpm2cpio libwebkitgtk-1.0-0
RUN apt-get install -y openvpn libxcb-shape0 bridge-utils libxcb-randr0 libsdl1.2debian acl libxcb-image0 libxcb-render-util0 libxcb-icccm4
RUN apt-get install -y python2.7 gettext make
RUN apt-get install -y gksu

ENV DEBIAN_FRONTEND noninteractive
# Replace 1000 with your user / group id
RUN export uid=1000 gid=1000 && \
    mkdir -p /home/developer && \
    echo "developer:x:${uid}:${gid}:Developer,,,:/home/developer:/bin/bash" >> /etc/passwd && \
    echo "developer:x:${uid}:" >> /etc/group && \
    echo "developer ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/developer && \
    chmod 0440 /etc/sudoers.d/developer && \
    chown ${uid}:${gid} -R /home/developer
RUN usermod -a -G audio,video developer


RUN chown -R developer:developer /home/developer
RUN chmod -R +rwx /home/developer
COPY installer-phase1.sh /home/developer/installer-phase1.sh
RUN chmod +x /home/developer/installer-phase1.sh
RUN echo "developer:devpass" | chpasswd
RUN echo "root:rootpass" | chpasswd
USER developer
ENV HOME /home/developer
RUN touch /home/developer/.Xauthority

CMD [ "/bin/bash", "-c", "/home/developer/installer-phase1.sh" ]